### ISSUE TITLE
Some sort of Session Error, L5.2

### ISSUE THREAD

**Issue by wutmikee** [artesaos/laravel-linkedin#2]
Hey, I've tried installing this package a few times. Was able to install package correctly (this time). 
When I try and run `return LinkedIn::getLoginUrl();` I get the following error...any ideas?

```
session_start(): open(/var/lib/php/sessions/sess_g009u0krgt2opthh5cmf4man60, O_RDWR) failed: Permission denied (13)
```

**Comment by mauri870** [comment]
Seems like a problem with your php.

Try change the path for your sessions on php.ini

```
session.save_path = /tmp
```

**Comment by wutmikee** [comment]
How do you mean? I'm using Homestead. 

Does this package use the Illuminate session?

**Comment by wutmikee** [comment]
So I was able to add this to the autoload.php file in Laravel, `ini_set('session.save_path', '/tmp');` but this seems like a hack. I couldn't find this folder on my Mac to change permissions...`/var/lib/php/sessions`. Any ideas? I'm using homestead/vagrant, Laravel 5.2.

**Comment by wutmikee** [comment]
Got it sorted. had to `vagrant ssh`...(duh!) and run the permission cmd there. `sudo chmod -R 777 /var/lib/php/sessions`
